// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6xzK658CpYdAx1rq5sjo4U6t7f2ZVCwE',
    appId: '1:818946949348:web:3a284620f8ccfb6f8a6cf1',
    messagingSenderId: '818946949348',
    projectId: 'fir-flutter-app-7b133',
    authDomain: 'fir-flutter-app-7b133.firebaseapp.com',
    storageBucket: 'fir-flutter-app-7b133.appspot.com',
    measurementId: 'G-2WW5N0DNH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkGSWYp3-SkLyBXELYF65JlAg-cg3D4C4',
    appId: '1:818946949348:android:095b0dc643a2c1f78a6cf1',
    messagingSenderId: '818946949348',
    projectId: 'fir-flutter-app-7b133',
    storageBucket: 'fir-flutter-app-7b133.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCacIGG0gFhsO8QD-tujm8dRVyBr0cFgwY',
    appId: '1:818946949348:ios:2b22dc2540b724838a6cf1',
    messagingSenderId: '818946949348',
    projectId: 'fir-flutter-app-7b133',
    storageBucket: 'fir-flutter-app-7b133.appspot.com',
    iosClientId: '818946949348-ptmp7ok2o050ar5c5mufk0nmja7dfaqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCacIGG0gFhsO8QD-tujm8dRVyBr0cFgwY',
    appId: '1:818946949348:ios:2b22dc2540b724838a6cf1',
    messagingSenderId: '818946949348',
    projectId: 'fir-flutter-app-7b133',
    storageBucket: 'fir-flutter-app-7b133.appspot.com',
    iosClientId: '818946949348-ptmp7ok2o050ar5c5mufk0nmja7dfaqf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseApp',
  );
}
